version: "3"
services:
  discord-bot-pokeclicker:
    build: .
    container_name: Discord-bot-pokeclicker
    command: ["pm2-runtime", "start", "ecosystem.config.js"]
    volumes:
      - ./:/usr/src/bot
      - /usr/src/bot/node_modules/
    working_dir: /usr/src/bot
    restart: unless-stopped
  update-discord-bot-pokeclicker:
    build: .
    container_name: Update-discord-bot-pokeclicker
    command: ["npm", "run", "build"]
    volumes:
      - ./:/usr/src/bot
      - /usr/src/bot/node_modules/
    working_dir: /usr/src/bot
    restart: "no"

# docker-compose up --force-recreate --build -d