name: Node.js CI

on:
  push:
    branches: [ v14 ]
  pull_request:
    branches: [ v14 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: npm i eslint
    - run: npm run test
